<?php
// $Id:
/**
 * @file
 */

/**
 * Implements hook_views_api().
 */
function views_infinite_scroll_views_api() {
  return array('api' => '3.0-alpha1');
}

/**
 * Implements hook_theme().
 */
function views_infinite_scroll_theme() {
  $path = drupal_get_path('module', 'views_infinite_scroll');

  // Some quasi clever array merging here.
  $base = array(
    'file' => 'views_infinite_scroll_theme.inc',
    'path' => "$path/theme",
  );

  // Our extra version of pager from pager.inc
  $hooks['views_infinite_scroll_pager'] = $base + array(
    'variables' => array(
      'tags' => array(),
      'limit' => 10,
      'element' => 0,
      'parameters' => array(),
    ),
    'pattern' => 'views_infinite_scroll_pager__',
  );
  return $hooks;
}

/**
 * Implements hook_views_ajax_data_alter().
 */
function views_infinite_scroll_views_ajax_data_alter(&$commands, $view) {
  switch ($view->query->pager->plugin_name) {
    case 'infinite_scroll':
      // Trigger the views_infinite_scroll_ajax_loaded event.
      $commands[] = ajax_command_invoke('.view-dom-id-' . $view->dom_id . ':parent', 'trigger', array('views_infinite_scroll_ajax_loaded'));
      break;
 }
}